### ISSUE TITLE
有个样本，不能提取图标，添加个从资源里面提取图标的功能吧

### ISSUE THREAD

**Issue by ohyeah521** [zxvzxv/ApkParse#4]
apk.get_icon() 输出内容如下：
resources.arsc/mipmap-mdpi/ic_launcher.png

 
样本下载地址：链接: https://pan.baidu.com/s/17tEoGzOTnPJfG574nGDCMw?pwd=8t7v 提取码: 8t7v

**Comment by zxvzxv** [comment]
实测可以正常提取，你直接按get_icon()输出的文件路径，把文件读出来就行了

```
print(apk.get_icon())
with open("/mnt/c/Users/user/Downloads/t.png",'wb') as fw:
    fw.write(apk.get_file(apk.get_icon().encode()))
```

**Comment by ohyeah521** [comment]
> 你直接按get_icon()输出的文件路径，把文件读出来就行了

确实可以，我之前写代码没加encode，所以报错了。
